sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kUosW4DkO+8yqa11afoS7W1s03F5htbeMYi3TITBx/6zCUzOij9CHg8EdgWgWQoQbYp0uz4zLT2XkU3XeorUkEK1GBRgDI/3vbaenfbUrm728PRogJhFlz87Ichp+iv9TDbTFvEquF2yxa0Shsd8TdgHma+X4eDT7vUoi6Ye1VYyJDoYtqwPmHzAUJnQ+9TxWPiYJsLsHwCNIA0jXEzzKSsQD3qkMRVBPIV2FWTQugG8hNZ7efBS+7Bc/FYNhCdL1gqYR/TS0bPpjEilJN7aQiN+upBXnLTgs9LwSk1DMVhSx6K+3KUmwMJ0qDralmuauEZzh0sBnmhcEjTG4zB6YbaPSa+zQt3FVy3W5BaATvmjuEcinuC56p0feHTCg+CazLxPUSzexMgCS3N7iV4jIqbV0rhA0h3Sr0U6c9Xqzz5pRQ2PsAz0f9f9KrTG7r4WPWvntxyp5R7BwW23mUNBy/33vsu46yWSshpMdrIaL0cLV21SiExUdvt5w/IDU9oZV6eFA4Ad8xV/Cpi5ezF+cUSrolsEKMG84yQtpzvNhS1HVGKRYRTV20kaxAhaFwSKEUQJfei4lfweC0UlFARUBnwcT4qvJ8jMMxqMrErtukN16dGaXsvISQb2kxCRO3UedYPk9UBfYM/URoMUv0D2eiP/jhRhrgtNCudozdK6j7I=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-French-Twins_4091
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy